name: Publish @port-labs/jq-node-bindings

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install node-gyp deps
        run: sudo apt-get install -y autoconf make libtool automake build-essential
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Upgrade npm for OIDC support
        run: npm install -g npm@10.9.7
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --provenance --tag=next --access public
        if: ${{ github.event.release.prerelease }}
      - run: npm publish --provenance --access public
        if: ${{ !github.event.release.prerelease }}