name: Publish @port-labs/jq-node-bindings

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

env:
  NPM_REGISTRY_URL: https://registry.npmjs.org
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Install node-gyp deps
        run: sudo apt-get install -y autoconf make libtool automake build-essential
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: ${{ env.NPM_REGISTRY_URL }}
      - name: Upgrade npm for OIDC support
        run: corepack enable && corepack prepare npm@latest --activate
      - run: npm ci
      - run: npm publish --provenance --tag=next --access public
        env:
          NODE_AUTH_TOKEN: ""
        if: ${{ github.event.release.prerelease }}
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ""
        if: ${{ !github.event.release.prerelease }}